### ISSUE TITLE
capistrano2 integration breaks on capistrano 2.9.0 with ruby 1.8.7 and rollbar 1.2.7

### ISSUE THREAD

**Issue by jpasichnyk** [rollbar/rollbar-gem#175]
```
/usr/lib/ruby/1.8/net/http.rb:560:in `initialize': can't convert Hash into String (TypeError)
        from /usr/lib/ruby/1.8/net/http.rb:560:in `open'
        from /usr/lib/ruby/1.8/net/http.rb:560:in `connect'
        from /usr/lib/ruby/1.8/timeout.rb:53:in `timeout'
        from /usr/lib/ruby/1.8/timeout.rb:101:in `timeout'
        from /usr/lib/ruby/1.8/net/http.rb:560:in `connect'
        from /usr/lib/ruby/1.8/net/http.rb:553:in `do_start'
        from /usr/lib/ruby/1.8/net/http.rb:542:in `start'
        from /usr/lib/ruby/1.8/net/http.rb:440:in `start'
        from /var/lib/gems/1.8/gems/rollbar-1.2.7/lib/rollbar/capistrano.rb:35:in `load_into'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:139:in `instance_eval'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:139:in `invoke_task_directly_without_callbacks'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:89:in `execute_task'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/callback.rb:38:in `call'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/callbacks.rb:128:in `trigger'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/callbacks.rb:128:in `each'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/callbacks.rb:128:in `trigger'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/callbacks.rb:29:in `invoke_task_directly'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:89:in `execute_task'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/execute.rb:46:in `execute_requested_actions_without_help'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/execute.rb:45:in `each'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions_without_help'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/help.rb:19:in `execute_requested_actions'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/execute.rb:34:in `execute!'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/lib/capistrano/cli/execute.rb:14:in `execute'
        from /var/lib/gems/1.8/gems/capistrano-2.9.0/bin/cap:4
        from /usr/local/bin/cap:19:in `load'
        from /usr/local/bin/cap:19
```

**Comment by DMA57361** [comment]
Also ran in to this problem, with version 1.4.5 of the Rollbar gem.

Problem is here https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/capistrano.rb#L35 since ruby 1.8.7 doesn't support the passing of an options hash to `Net::HTTP.start`.

It would probably work if you were to replace this
```
Net::HTTP.start(uri.host, uri.port, :use_ssl => true) do |http|
  http.request(request)
end
```
with something in the vein of this
```
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.request(request)
```
I tried exactly that via a bundle open on the gem and it worked successfully, although I didn't check how well any other ruby versions would take to it.

In the meantime, anyone else with the problem could backport 1.9.2's `Net::HTTP.start` to 1.8.7. I've put a close approximation of it here https://gist.github.com/DMA57361/eddf18def093a33bcc1c. I just require it the deploy.rb file before rollbar and everything works a treat.

**Comment by jondeandres** [comment]
@DMA57361 thanks for the details of the error, hope we can solve this soon.
