### ISSUE TITLE
Rollbar 2.3.0 does not report any error

### ISSUE THREAD

**Issue by deepj** [rollbar/rollbar-gem#307]
This error is occurred in my Rails application but Rollbar does not report it.

```
F, [2015-09-23T13:54:01.062148 #3993] FATAL -- :
ActiveRecord::NoDatabaseError (FATAL:  database "database_production" does not exist
):
  activerecord (4.2.4) lib/active_record/connection_adapters/postgresql_adapter.rb:665:in `rescue in connect'
  activerecord (4.2.4) lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `connect'
  activerecord (4.2.4) lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
  activerecord (4.2.4) lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
  activerecord (4.2.4) lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
  /Users/deepj/.rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
  /Users/deepj/.rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
  activerecord (4.2.4) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.2.4) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.2.4) lib/active_record/query_cache.rb:51:in `restore_query_cache_settings'
  activerecord (4.2.4) lib/active_record/query_cache.rb:43:in `rescue in call'
  activerecord (4.2.4) lib/active_record/query_cache.rb:31:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  newrelic_rpm (3.13.1.300) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.14.0) lib/puma/server.rb:541:in `handle_request'
  puma (2.14.0) lib/puma/server.rb:388:in `process_client'
  puma (2.14.0) lib/puma/server.rb:270:in `block in run'
  puma (2.14.0) lib/puma/thread_pool.rb:106:in `call'
  puma (2.14.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

If I trigger manually something like `Rollbar.error('Unexpected input')` in Rails console. It is reported.

My **config/initializers/rollbar.rb**:

```ruby
# we want to have Rollbar available only in production environment

if Rails.env.production?
  require 'rollbar/rails'

  Rollbar.configure do |config|
    # Without configuration, Rollbar is enabled in all environments.
    # To disable in specific environments, set config.enabled=false.

    config.access_token = 'some-token'

    config.enabled = true

    # By default, Rollbar will try to call the `current_user` controller method
    # to fetch the logged-in user object, and then call that object's `id`,
    # `username`, and `email` methods to fetch those properties. To customize:
    # config.person_method = "my_current_user"
    # config.person_id_method = "my_id"
    # config.person_username_method = "my_username"
    # config.person_email_method = "my_email"

    # If you want to attach custom data to all exception and message reports,
    # provide a lambda like the following. It should return a hash.
    # config.custom_data_method = lambda { {:some_key => "some_value" } }

    # Add exception class names to the exception_level_filters hash to
    # change the level that exception is reported at. Note that if an exception
    # has already been reported and logged the level will need to be changed
    # via the rollbar interface.
    # Valid levels: 'critical', 'error', 'warning', 'info', 'debug', 'ignore'
    # 'ignore' will cause the exception to not be reported at all.
    # config.exception_level_filters.merge!('MyCriticalException' => 'critical')
    #
    # You can also specify a callable, which will be called with the exception instance.
    # config.exception_level_filters.merge!('MyCriticalException' => lambda { |e| 'critical' })

    # Enable asynchronous reporting (uses girl_friday or Threading if girl_friday
    # is not installed)
    config.use_async = true
    # Supply your own async handler:
    # config.async_handler = Proc.new { |payload|
    #  Thread.new { Rollbar.process_payload_safely(payload) }
    # }

    # Enable asynchronous reporting (using sucker_punch)
    # config.use_sucker_punch

    # Enable delayed reporting (using Sidekiq)
    # config.use_sidekiq
    # You can supply custom Sidekiq options:
    # config.use_sidekiq 'queue' => 'my_queue'
  end
end
```

In **Gemfile** I have something like this:

```
group :production do
  gem 'newrelic_rpm', '3.13.1.300'
  gem 'puma',         '2.14.0',    require: false
  gem 'rollbar',      '2.3.0',     require: false
end
```

**Comment by jondeandres** [comment]
@deepj this error is happening before the Rollbar middleware received `#call`, so we cannot report that error. Seems you have an error in your database config or similar.

I'm not sure we can set add our middleware before in the Rails middlewares chain.

**Comment by deepj** [comment]
@jondeandres One of the solution is remove `require: false` from `gem 'rollbar'` in **Gemfile**. Then `require 'rollbar/rails'` in the rollbar generated initializer is not necessary (I also removed it from the initializer). At least for me it looks like a bug when `require 'rollbar/rails'` doesn't enable automatic reporting errors.

**Comment by jondeandres** [comment]
@deepj why do you have `require: false` in production? You'll need to require it, at least, in your rollbar initializer.

**Comment by deepj** [comment]
@jondeandres  Because it would be double require of rollbar. One in Gemfile, second one in the initializer. It's the reason.

**Comment by jondeandres** [comment]
@deepj I think I'm not understanding this. You only need the `require 'rollbar'` in your Rollbar initializer. Doesn't that work for you?

If you don't want Rollbar to report errors on other environment than production, then you can just disable it with `config.enabled = Rails.env.production?`.

**Comment by deepj** [comment]
https://github.com/rollbar/rollbar-gem/blob/master/lib/generators/rollbar/templates/initializer.rb#L1

The initializer use `require 'rollbar/rails'`.

Rails loads Gemfile and every single gem (except ones with `require false`) there. In this point Rollbar is loaded first time. Then Rails starts loading initializers. In this point Rollbar is loaded again second time due to `require 'rollbar/rails'`. https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/rails.rb#L1

The problem here is `rollbar/rails` is confusing because Rollbar was loaded once. I would expect I don't need to require Rollbar in **Gemfile**. But it is not true because some code of Rollbar needs to be loaded before initializers. Then the `require` is useless. I hope it's clear now.

Simple solution for Rollbar. Remove the require from the template.

> If you don't want Rollbar to report errors on other environment than production, then you can just disable it with config.enabled = Rails.env.production?.

I don't want to load Rollbar and its code in any other environment than in *production*. It just slow downs things and eats memory in development or test environment.

**Comment by jondeandres** [comment]
@deepj yes, I think you are right.

we should remove `rollbar/rails.rb` file and remove the require from the template since we have https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/railtie.rb and that's loaded when Rollbar is loaded and `Rails` constant is defined.

Thanks @deepj! I think we'll fix this soon.

**Comment by jondeandres** [comment]
@deepj I've been looking at this. It's true that we are doing like double requires somewhere. But I'm not sure this is causing any real problem.

We'll remove `rollbar/rails.rb` and the `require` from the template. However, I'd say anything of this is related to the description of the issue you opened.

Are you still having problems with this? I still think this is a problem since a middleware is crashing before our middleware was called.

Thanks.

**Comment by deepj** [comment]
@jondeandres No. I think this "issue" can be closed. And for the removing `rollbar/rails.rb` and the `require` in the template :+1: Thanks!
