### ISSUE TITLE
undefined method `configure' for Rollbar:Module (NoMethodError)

### ISSUE THREAD

**Issue by KamilLelonek** [rollbar/rollbar-gem#344]
I upgraed `Rollbar` from `1.5.3` to `2.6.1` and I get the error from issue's title.

I tried to recreate `Rollbar` configuration by running:

```bash
rails generate rollbar POST_SERVER_ITEM_ACCESS_TOKEN
```

but the problem remains the same.

What can be wrong?

**Comment by jondeandres** [comment]
Hi @KamilLelonek, thanks for the report. Do you have backtrace of this? I will look into this today and contact you here.

Thanks.

**Comment by KamilLelonek** [comment]
```bash
/Users/user/project/config/initializers/rollbar.rb:3:in `<top (required)>': undefined method `configure' for Rollbar:Module (NoMethodError)
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
        from /Users/user/project/config/environment.rb:3:in `<top (required)>'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.4/lib/spring/application.rb:92:in `preload'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.4/lib/spring/application.rb:143:in `serve'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.4/lib/spring/application.rb:131:in `block in run'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.4/lib/spring/application.rb:125:in `loop'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.4/lib/spring/application.rb:125:in `run'
        from /Users/user/.rvm/gems/ruby-2.2.1/gems/spring-1.4.4/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/user/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
```

**Comment by jondeandres** [comment]
@KamilLelonek your problem is while executing `rails generate` or after execute that and start the server?

**Comment by KamilLelonek** [comment]
Everything which is related to running an initializer. So basically I can generate `Rollbar` config, but I cannot start a server after that.

**Comment by jondeandres** [comment]
Can you paste your Rollbar initializer? Has that file a `require 'rollbar'` line?

THanks.

**Comment by KamilLelonek** [comment]
```ruby
require 'rollbar/rails'

Rollbar.configure do |config|
  config.access_token = Rails.application.secrets.rollbar_access_token

  config.enabled = Rails.env.production?

  config.project_gems = %w(...)
end
```

**Comment by jondeandres** [comment]
@KamilLelonek change that `require 'rollbar/rails'` with `require 'rollbar'`.

Tell me if that works.

Thanks.

**Comment by KamilLelonek** [comment]
It does, what was the reason for this change? I couldn't find this in any changelog or upgrading process.

**Comment by jondeandres** [comment]
Hi @KamilLelonek, this was changed inhttps://github.com/rollbar/rollbar-gem/blob/master/CHANGELOG.md#240. You have details there.

Cheers.

**Comment by unchris** [comment]
@jondeandres we recently stumbled on this having used the `require 'rails/rollbar'` in the past. We changed it to `require 'rollbar'` and it worked fine.

However, we deleted the file and re-ran `rails generate rollbar` which produced a file which did not include the needed `require 'rollbar'`

I don't mind making a PR if it's as simple as changing the top of `lib/generators/rollbar/templates/initializer.rb` to add `require 'rollbar'`

**Comment by jondeandres** [comment]
@unchris I think Rails will load `rollbar` since it's defined in your Gemfile. So probably everything should work as it is actually.

I agree with you that probably is more correct having `require 'rollbar'` in the template. If you want to open a PR you're welcome :).

Thanks.

**Comment by unchris** [comment]
@jondeandres ahh you know what? it's our mistake. Looks like we only have rollbar in the gemfile for `:production` and `:test`. Thanks for reminding me about the Gemfile here. No issues!

**Comment by jondeandres** [comment]
awesome :smile:. Thanks!

**Comment by simonc** [comment]
Stumbled upon the same issue. Just a quick note, following semver the module should have stayed until v3. No big trouble but that's important for a lot of people 😉

**Comment by jondeandres** [comment]
@simonc can you tell us how your rollbar initializer is?

**Comment by simonc** [comment]
@jondeandres it was containing `require "rollbar/rails"` and we fixed it using `require "rollbar"`. What I meant to say is that upgrading to a minor version should not have broken our app, we should have seen a warning telling us to change this line and that it would not be supported in v3. See what I mean? 😊
