### ISSUE TITLE
Rails – undefined method `+' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by lukehorvat** [rollbar/rollbar-gem#391]
Hi I'm trying to use Rollbar in a Rails app, but I encounter an error every time my app starts:

```
=> Booting Puma
=> Rails 4.2.5 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rollbar-2.8.0/lib/rollbar/railtie.rb:36:in `block (2 levels) in <class:Railtie>': undefined method `+' for nil:NilClass (NoMethodError)
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rollbar-2.8.0/lib/rollbar.rb:822:in `preconfigure'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rollbar-2.8.0/lib/rollbar/railtie.rb:31:in `block in <class:Railtie>'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /Users/luke/dev/my-app/config/environment.rb:5:in `<top (required)>'
	from /Users/luke/dev/my-app/config.ru:3:in `require'
	from /Users/luke/dev/my-app/config.ru:3:in `block in <main>'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /Users/luke/dev/my-app/config.ru:in `new'
	from /Users/luke/dev/my-app/config.ru:in `<main>'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/server.rb:61:in `app'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/server.rb:78:in `start'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/luke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

My configuration in `config/initializers/rollbar.rb` is pretty minimal:

```ruby
require 'rollbar'

Rollbar.configure do |config|
  config.enabled = Rails.env.production?
  config.access_token = ENV['ROLLBAR_ACCESS_TOKEN']
  config.environment = Rails.env
end
```

And  `Gemfile`:

```ruby
gem 'rollbar'
```

So I don't see what I could be doing wrong here. What is causing the error?

**Comment by jondeandres** [comment]
Hi @lukehorvat, can you open a Rails console and run this?

```ruby
::Rails.application.class.parent_name
```

How do you define your app class in config/application.rb?

Thanks

**Comment by lukehorvat** [comment]
My `config/application.rb` looks like this:

```ruby
require File.expand_path("../boot", __FILE__)
require "rails/all"

Bundler.require(*Rails.groups) # Require the gems listed in Gemfile.

class Application < Rails::Application

...

end
```

Running `::Rails.application.class.parent_name` returns `nil`...

**Comment by jondeandres** [comment]
@lukehorvat sounds interesting...that `config/application.rb` was generated by `rails` command? Usually `class Application` is nested in another module:

```ruby
module MyAwesomeApplication
  class Application < Rails::Application
```

So I'd say something wrong is being generated or configured.

**Comment by lukehorvat** [comment]
Ah, so it needs to be wrapped in a module. I removed the module definition myself some time ago since my app didn't need it.

Thank you.

**Comment by jondeandres** [comment]
Thanks to you @lukehorvat

**Comment by RavinderSinghPB** [comment]
check for the master.key file in config.
