### ISSUE TITLE
Incompability with rake (11.0.1): cannot determine rake version

### ISSUE THREAD

**Issue by pirkka** [rollbar/rollbar-gem#396]
/gems/rollbar-2.8.2/lib/rollbar/rake.rb:23:in `patch?': undefined method `split' for nil:NilClass (NoMethodError)

Getting the above error with rake 11.0.1, looks like patch method is simply unable to determine what version of Rake is running.

Rollbar gem verison used is 2.8.2.

**Comment by jondeandres** [comment]
Hi @pirkka, thanks for opening this issue. We hope to fix this this week.

Thanks.

**Comment by loed-idzinga** [comment]
Running into the same issue, copied the output from the trace. 

```bash
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
<path>/2.3.0/lib/ruby/gems/2.3.0/gems/rollbar-2.8.2/lib/rollbar/rake.rb:23:in `patch?'
<path>/2.3.0/lib/ruby/gems/2.3.0/gems/rollbar-2.8.2/lib/rollbar/rake.rb:6:in `patch!'
<path>/2.3.0/lib/ruby/gems/2.3.0/gems/rollbar-2.8.2/lib/rollbar/rake.rb:38:in `<top (required)>'
<path>/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
<path>s/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
<path>/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
<path>/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
<path>/2.3.0/lib/ruby/gems/2.3.0/gems/rollbar-2.8.2/lib/rollbar.rb:884:in `require_hooks'
<path>/2.3.0/lib/ruby/gems/2.3.0/gems/rollbar-2.8.2/lib/rollbar.rb:863:in `prepare'
<path>/2.3.0/lib/ruby/gems/2.3.0/gems/rollbar-2.8.2/lib/rollbar.rb:833:in `configure'
<project path>/config/initializers/rollbar.rb:1:in `<top (required)>'
```

**Comment by jondeandres** [comment]
Thanks @loed-idzinga, I think https://github.com/rollbar/rollbar-gem/pull/397 will resolve the problem.

Thanks!

**Comment by jrasanen** [comment]
I wonder if the error I get is related to this one? Followed the onboarding process and got "NoMethodError: undefined method `split' for nil:NilClass"

Steps to reproduce:

* Create an empty rails project
* Add pg and rollbar to Gemfile
```ruby
gem 'rollbar', '~> 2.7.1'
gem 'pg'
```
* rails generate rollbar XXXXX
* rake rollbar:test

and I get an error,

```shell
$ rake rollbar:test
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/rollbar-2.7.1/lib/rollbar/rake.rb:23:in `patch?'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/rollbar-2.7.1/lib/rollbar/rake.rb:6:in `patch!'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/rollbar-2.7.1/lib/rollbar/rake.rb:38:in `<top (required)>'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/rollbar-2.7.1/lib/rollbar.rb:790:in `require_hooks'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/rollbar-2.7.1/lib/rollbar.rb:755:in `configure'
/Users/jrasanen/Development/ror/rollbarbug/config/initializers/rollbar.rb:1:in `<top (required)>'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/Users/jrasanen/Development/ror/rollbarbug/config/environment.rb:5:in `<top (required)>'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/Users/jrasanen/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => rollbar:test => environment
(See full trace by running task with --trace)
```

**Comment by jondeandres** [comment]
Hi @jrasanen, we fixed this with https://github.com/rollbar/rollbar-gem/pull/397. If you upgrade to the latest version you have it fixed.

**Comment by jrasanen** [comment]
Ok thanks!

I guess the on-boarding still has the old version, it tells to install "~> 2.7.1". Maybe it should be "~> 2.7"? It would then match the latest version too.

**Comment by brianr** [comment]
Thanks @jrasanen - we'll get those docs updated.
