### ISSUE TITLE
Not able to filter out ActionController::Routing errors

### ISSUE THREAD

**Issue by phillipb** [rollbar/rollbar-gem#511]
I've been trying to filter out routing errors, but haven't been successful. The stack trace appears to say the exception was ignored, but for some reason it still gets reported. I saw a strange `resuce` in `lib/rollbar/middleware/rails/show_exceptions.rb:23`, but I'm not familiar enough with the code to say that that's the issue.

Rollbar Initializer:
```
require 'rollbar/rails'
require 'rollbar/logger'

Rollbar.configure do |config|
  config.access_token = ENV['ROLLBAR_ACCESS_TOKEN']

  config.environment = ENV['ROLLBAR_ENV']

  # Here we'll disable in 'test':
  if Rails.env.test? or not ENV['ROLLBAR_ACCESS_TOKEN']
    config.enabled = false
  end


  Rails.logger.extend(ActiveSupport::Logger.broadcast(Rollbar::Logger.new))

  config.exception_level_filters.merge!({
    'ActionController::RoutingError' => 'ignore'
  })

  config.exception_level_filters.merge!({
    'ActionController::RoutingError' => lambda { |error| 'ignore' }
  })

end
```

StackTrace: 
```
13:13:44 web.1     | Started GET "/asdfasdfasdfasdfasdf" for 127.0.0.1 at 2016-08-23 13:13:44 -0500
13:13:47 web.1     | [Rollbar] Reporting exception: No route matches [GET] "/asdfasdfasdfasdfasdf"
13:13:52 web.1     | [Rollbar] Exception not reported because it was ignored
13:13:52 web.1     | ActionController::RoutingError (No route matches [GET] "/asdfasdfasdfasdfasdf"):
13:13:52 web.1     |   actionpack (4.1.15) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
13:13:52 web.1     |   rollbar (2.12.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
13:13:52 web.1     |   actionpack (4.1.15) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
13:13:52 web.1     |   railties (4.1.15) lib/rails/rack/logger.rb:38:in `call_app'
13:13:52 web.1     |   railties (4.1.15) lib/rails/rack/logger.rb:20:in `block in call'
13:13:52 web.1     |   activesupport (4.1.15) lib/active_support/tagged_logging.rb:68:in `block in tagged'
13:13:52 web.1     |   activesupport (4.1.15) lib/active_support/tagged_logging.rb:26:in `tagged'
13:13:52 web.1     |   activesupport (4.1.15) lib/active_support/tagged_logging.rb:68:in `tagged'
13:13:52 web.1     |   railties (4.1.15) lib/rails/rack/logger.rb:20:in `call'
13:13:52 web.1     |   quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
13:13:52 web.1     |   actionpack (4.1.15) lib/action_dispatch/middleware/request_id.rb:21:in `call'
13:13:52 web.1     |   rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
13:13:52 web.1     |   rack (1.5.5) lib/rack/runtime.rb:17:in `call'
13:13:52 web.1     |   activesupport (4.1.15) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
13:13:52 web.1     |   rack (1.5.5) lib/rack/lock.rb:17:in `call'
13:13:52 web.1     |   actionpack (4.1.15) lib/action_dispatch/middleware/static.rb:84:in `call'
13:13:52 web.1     |   rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
13:13:52 web.1     |   railties (4.1.15) lib/rails/engine.rb:514:in `call'
13:13:52 web.1     |   railties (4.1.15) lib/rails/application.rb:144:in `call'
13:13:52 web.1     |   rack (1.5.5) lib/rack/lock.rb:17:in `call'
13:13:52 web.1     |   rack (1.5.5) lib/rack/content_length.rb:14:in `call'```

**Comment by jondeandres** [comment]
@phillipb can you check if the rollbar middleware is being executed for those `ActionController::RoutingError`? It looks like the middleware may not be added in the correct position in the middleware chain.

**Comment by jondeandres** [comment]
@phillipb if you have `Rails.logger.extend(ActiveSupport::Logger.broadcast(Rollbar::Logger.new))` in the config, you will log something like https://rollbar.com/Rollbar/rollbar-gem/items/6846/. That is because `Rollbar::Logger` doesn't receive the exception, but just the message and the level. We cannot filter the logs.

So, you are filtering the exception report itself, but not the log. We can't do something with this.
