### ISSUE TITLE
Problem with rails validations @ 2.13.2

### ISSUE THREAD

**Issue by plentz** [rollbar/rollbar-gem#534]
The rails 5 default validation for `belongs_to` being required(unless you use `optional: true`) stop working when updating from `2.12.0` to `2.13.2`

``` ruby
class PhoneNumber < ApplicationRecord
  belongs_to :phone_book
end
```

this test fails using `2.13.2` and works using `2.12.0`

``` ruby
require 'rails_helper'

RSpec.describe PhoneNumber, type: :model do
  describe "validation" do
    it "requires a phone_book" do
      pn = PhoneNumber.new
      expect(pn.valid?).to be false
      expect(pn.errors).to have_key(:phone_book)
    end
  end
end
```

**Comment by jondeandres** [comment]
@plentz I'm not sure exactly which relation this has with the gem. Can you please explain farther? Thanks!

**Comment by plentz** [comment]
@jondeandres I know, it's super weird (it took me a few hours to figure it out that was rollbar that was generating this error). Basically what happens: rails 5, by default, requires `belongs_to` to be not null(unless you sai that it's `optional: true`). That test was written to ensure that the validation still happens. After updating rollbar, the test started to fail, since the record now reports it as `valid`. The weird part is, if I change that line from `belongs_to :phone_book` to `belongs_to :phone_book, optional: false`(the default config, but making it explicity), the test works again.


```
~/Projects/web (permissions)$ git st
On branch permissions
nothing to commit, working tree clean
~/Projects/web (permissions)$ rspec spec/models/phone_number_spec.rb 
.

Finished in 0.08974 seconds (files took 5.39 seconds to load)
1 example, 0 failures

~/Projects/web (permissions)$ bundle update rollbar
Fetching gem metadata from https://rails-assets.org/...
Fetching version metadata from https://rails-assets.org/..
Fetching gem metadata from https://rails-assets.org/...
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rails-assets.org/..
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rails-assets.org/..
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies.....
Using rake 11.3.0
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.2
Using addressable 2.4.0
Using net-ssh 3.2.0
Using execjs 2.7.0
Using jmespath 1.3.1
Using babel-source 5.8.35
Using bcrypt 3.1.11
Using sass 3.4.22
Using bundler 1.12.3
Using byebug 9.0.5
Using capistrano-harrow 0.5.3
Using puma 3.6.0
Using cliver 0.3.2
Using coffee-script-source 1.10.0
Using method_source 0.8.2
Using thor 0.19.1
Using connection_pool 2.2.0
Using diff-lcs 1.2.5
Using ffi 1.9.14
Using forgery 0.6.0
Using jasmine-core 2.5.2
Using phantomjs 2.1.1.0
Using multi_json 1.12.1
Using rb-fsevent 0.9.7
Using ruby_dep 1.4.0
Using mercenary 0.3.6
Using newrelic_rpm 3.16.3.323
Using oj 2.17.4
Using pg 0.19.0
Using rails-assets-blueimp-canvas-to-blob 3.3.0
Using rails-assets-blueimp-load-image 2.6.2
Using rails-assets-blueimp-tmpl 3.4.0
Using rails-assets-dragula 3.7.2
Using rails-assets-handlebars 4.0.5
Using rails-assets-jquery 2.2.3
Using rails-assets-select2 4.0.3
Using rails-assets-svgxuse 1.1.22
Using rails-assets-tether 1.3.7
Using tilt 2.0.5
Using rspec-support 3.5.0
Using temple 0.7.7
Using spring 1.7.2
Using i18n-js 3.0.0.rc14
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using rack-test 0.6.3
Using sprockets 3.6.3
Using websocket-driver 0.6.4
Using mime-types 3.1
Using net-scp 1.2.1
Using autoprefixer-rails 6.5.0
Using uglifier 3.0.2
Using aws-sdk-core 2.6.4
Using babel-transpiler 0.7.0
Using scss_lint 0.50.2
Using coffee-script 2.4.1
Using rb-inotify 0.9.7
Using sassc 1.10.0
Using jasmine 2.4.0
Using rollbar 2.13.2 (was 2.12.0)
Using rails-assets-ionrangeslider 2.1.4
Using rails-assets-jquery-file-upload 9.12.5
Using rails-assets-jquery-maskedinput 1.4.1
Using rails-assets-jquery-ujs 1.2.0
Using rails-assets-spectrum 1.8.0
Using rspec-core 3.5.3
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using slim 3.0.7
Using activesupport 5.0.0.1
Using loofah 2.0.3
Using xpath 2.0.0
Using mail 2.6.4
Using sshkit 1.11.3
Using bootstrap 4.0.0.alpha3
Using aws-sdk-resources 2.6.4
Using listen 3.1.5
Using rspec-collection_matchers 1.1.2
Using rspec 3.5.0
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.0.0.1
Using factory_girl 4.7.0
Using intercom-rails 0.3.2
Using jbuilder 2.6.0
Using rails-html-sanitizer 1.0.3
Using capybara 2.9.1
Using airbrussh 1.1.1
Using aws-sdk 2.6.4
Using spring-watcher-listen 2.0.0
Using svgeez 0.2.3
Using activejob 5.0.0.1
Using activerecord 5.0.0.1
Using actionview 5.0.0.1
Using poltergeist 1.10.0
Using capistrano 3.6.1
Using actionpack 5.0.0.1
Using capistrano-bundler 1.1.4
Using capistrano3-puma 1.2.1
Using actioncable 5.0.0.1
Using actionmailer 5.0.0.1
Using railties 5.0.0.1
Using sprockets-rails 3.1.1
Using rails-controller-testing 1.0.1
Using capistrano-rails 1.1.8
Using coffee-rails 4.1.1
Using factory_girl_rails 4.7.0
Using rails-i18n 5.0.0
Using rspec-rails 3.5.2
Using slim-rails 3.1.1
Using rails 5.0.0.1
Using sassc-rails 1.2.1
Using react-rails 1.7.1
Bundle updated!
~/Projects/web (permissions)$ git st
On branch permissions
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Gemfile.lock

no changes added to commit (use "git add" and/or "git commit -a")
~/Projects/web (permissions)$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 58ce868..f51326a 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -226,7 +226,7 @@ GEM
       execjs
       rails (>= 3.2)
       tilt
-    rollbar (2.12.0)
+    rollbar (2.13.2)
       multi_json
     rspec (3.5.0)
       rspec-core (~> 3.5.0)
~/Projects/web (permissions)$ rspec spec/models/phone_number_spec.rb 
F

Failures:

  1) PhoneNumber validation requires a phone_book
     Failure/Error: expect(pn.valid?).to be false
     
       expected false
            got true
     # ./spec/models/phone_number_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ./app/models/tenant.rb:26:in `scope_schema'
     # ./spec/models/phone_number_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.07334 seconds (files took 5.36 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/models/phone_number_spec.rb:8 # PhoneNumber validation requires a phone_book

~/Projects/web (permissions)$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 58ce868..f51326a 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -226,7 +226,7 @@ GEM
       execjs
       rails (>= 3.2)
       tilt
-    rollbar (2.12.0)
+    rollbar (2.13.2)
       multi_json
     rspec (3.5.0)
       rspec-core (~> 3.5.0)
diff --git a/app/models/phone_number.rb b/app/models/phone_number.rb
index 2aa8588..1f6e3aa 100644
--- a/app/models/phone_number.rb
+++ b/app/models/phone_number.rb
@@ -1,3 +1,3 @@
 class PhoneNumber < ApplicationRecord
-  belongs_to :phone_book
+  belongs_to :phone_book, optional: false
 end
~/Projects/web (permissions)$ rspec spec/models/phone_number_spec.rb 
.

Finished in 0.08686 seconds (files took 4.8 seconds to load)
1 example, 0 failures

```

**Comment by jondeandres** [comment]
so weird yes...I'll need to debug this more. if you find something else about validations share it here please.

**Comment by dsander** [comment]
I noticed that behavior as well and did a bit of bisecting. The commit that introduced the bug is 84b95ea202aacda18c8acfc085906d2e11437b80.
@jondeandres If you are looking for a way to reproduce it clone `https://github.com/dsander/huginn.io`, switch to the `add-rollbar` branch,  update the rollbar gem and run `rspec ./spec/models/scenario_spec.rb:19`

**Comment by dsander** [comment]
It looks like not the code is causing the error, but using `ActiveRecord::Base` seems to trigger rails auto loader which then messes with some other modules. Calling the code in an ActiveSupport callback fixes the issue for me:

```ruby
    ActiveSupport.on_load(:active_record) do
      if defined?(ActiveRecord::Base)
        ActiveRecord::Base.class_eval do
          include Rollbar::ActiveRecordExtension
        end
      end
    end
```

**Comment by jondeandres** [comment]
Hey @dsander, thank you very much for investigating this! Let me try it and checking everything is ok and we will push a fix with this.

Thanks!

**Comment by jondeandres** [comment]
I've been thinking about this. The code in `validations.rb` includes a module in `ActiveModel::Validations`, but if `ActiveRecord::Base` is already defined, we need to include it in `ActiveRecord::Base` itself, since it has `ActiveModel::Validations` already included on it.

Doing the check inside the `on_load(:active_support)` callback means that `ActiveRecord` is obviously loaded and defined. But we don't detect the case we are detecting right now.

I think we would need, maybe, something like:

```ruby
active_support_was_defined = defined?(ActiveRecord::Base)

    ActiveSupport.on_load(:active_record) do
      if active_support_was_defined
        ActiveRecord::Base.class_eval do
          include Rollbar::ActiveRecordExtension
        end
      end
    end
```

Let me check this during next days and I'll write an update here. Thanks.

**Comment by levent** [comment]
Version 2.14.0 seems to have introduced a similar issue with has_many through associations. I will try and find time to investigate this.
