### ISSUE TITLE
Failsafe: IOError: "not opened for reading"

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-gem#694]
user is receiving the below error:

```
Failsafe from rollbar-gem. IOError: "not opened for reading" in /app/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/json/encoding.rb:207:in `each': error in process_item
```

internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/813334/conversations/14915194144

**Comment by KieranP** [comment]
Same here:

```
#4994 Failsafe from rollbar-gem. IOError: "not opened for reading" in /home/work/app/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22.5/lib/active_support/json/encoding.rb:207:in `each': error in process_item
```

**Comment by ArturMoczulski** [comment]
Added to the upcoming release

**Comment by jondeandres** [comment]
This is related to a bug in active_support, https://github.com/rails/rails/issues/26132. It's gonna be complicated prepare a fix in the gem for it, but there are ways to try to avoid the problem.

For this we'll need some debugging work and we'd need to know the `item.payload` on `Rollbar::Notifier#send_item`.

Also, it seems this might be fixed on more recent versions of rails https://github.com/rails/rails/pull/30953/files
