### ISSUE TITLE
Mock out Redis in tests instead of requiring a running Redis instance

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-gem#724]
When I run `rake spec` on `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]` I get the following test failure:

```
2) Rollbar::Item#dump with Redis instance in payload and ActiveSupport is enabled dumps to JSON correctly
     Failure/Error: redis.set('foo', 'bar')
     
     Redis::CannotConnectError:
       Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis/client.rb:344:in `rescue in establish_connection'
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis/client.rb:329:in `establish_connection'
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis/client.rb:99:in `block in connect'
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis/client.rb:98:in `connect'
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis/client.rb:363:in `ensure_connected'
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
     # /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
     # /usr/local/rvm/gems/ruby-2.3.1/gems/redis-4.0.1/lib/redis.rb:779:in `set'
     # ./spec/rollbar/item_spec.rb:683:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # IO::EINPROGRESSWaitWritable:
     #   Operation now in progress - connect(2) would block
     #   /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/socket.rb:1207:in `__connect_nonblock'
```

The test suit shouldn't require a running Redis instance.

The reference to the Redis instance should be replaced with a mock object.

**Comment by ArturMoczulski** [comment]
@waltjones submitted a PR which modifies the test and removes the dependency on the Redis client.

Meanwhile, I did further investigation in what was happening there and found that calling `to_a` on `Redis::Connection::TCPSocket` hangs Ruby. I will check if this is happening in their `master` still and if so submit a GitHub issue in their repo.

**Comment by ArturMoczulski** [comment]
An issue in Redis repo created: https://github.com/redis/redis-rb/issues/830
