### ISSUE TITLE
SSL certificate error when using deploy tracking

### ISSUE THREAD

**Issue by robjlucas** [rollbar/rollbar-gem#873]
Deploy tracking has recently started failing with SSL certificate errors:

```
#<Thread:0x00007f8e320e7e60@/Users/user/.rvm/gems/ruby-2.5.0/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /Users/user/.rvm/gems/ruby-2.5.0/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/user/.rvm/gems/ruby-2.5.0/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as user@whatever.org: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (SSHKit::Runner::ExecuteError)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as user@whatever.org: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)


Caused by:
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

Tasks: TOP => rollbar:deploy
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as user@whatever.org: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
```

**Comment by waltjones** [comment]
@robjlucas I can't tell from that output whether it fails connecting to the Rollbar API or one of your servers. I haven't heard about any cert issues with the Rollbar API though. Do you have further insight on this?

**Comment by robjlucas** [comment]
This did turn out to be a local issue: the CA certificates needed to be updated.

Since I am using RVM, in my case this was a simple matter of:

`rvm osx-ssl-certs update all`
