### ISSUE TITLE
FrozenError inside rollbar code

### ISSUE THREAD

**Issue by andreasst** [rollbar/rollbar-gem#883]
When passing extra data to Rollbar.log that includes frozen arrays, the Rollbar code throws an exception while trying to copy it.

For example,
```
irb(main):009:0> Rollbar.info(StandardError.new("freeze testing"), {params: [1,2].freeze})
[patch] reporting rollbar internal error
can't modify frozen Array
[
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/util.rb:58:in `clear'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/util.rb:58:in `deep_copy'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/util.rb:76:in `block in deep_merge'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/util.rb:70:in `each_key'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/util.rb:70:in `deep_merge'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/item.rb:157:in `build_extra'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/item.rb:149:in `build_backtrace_body'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/item.rb:143:in `build_body'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/item.rb:85:in `build_data'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/item.rb:62:in `build'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/notifier.rb:435:in `build_item'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/notifier.rb:379:in `report'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/notifier.rb:144:in `log'",
  "/var/app/vendor/bundle/ruby/2.6.0/gems/rollbar-2.15.5/lib/rollbar/notifier.rb:159:in `info'",
  "/var/app/vendor/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `info'",
```

I think the right fix would be to replace the calls to `clone` with `dup`: https://github.com/rollbar/rollbar-gem/blob/0e773fd1624e922a2702efe670a474acb2f16958/lib/rollbar/util.rb#L68

**Comment by waltjones** [comment]
@andreasst Thank you for the report! We'll try to get this in the next release.
