### ISSUE TITLE
SystemStackError when logging rollbar error during Route resolution

### ISSUE THREAD

**Issue by rdunlop** [rollbar/rollbar-gem#926]
Using:
- Rails 5.2.3
- Rollbar 2.23.1
- ruby 2.4.5

I have a constraint in my routes.rb like:
```
namespace :v2, constraints: V2::FeatureFlagConstraint.new do
  resource :photo_op
end
```

And in my Constraint checking code, sometimes I call `Rollbar.info("Nil entry")`.

If I do this, it causes an infinite loop, and a `SystemStackError`, (I think it's trying to include additional information in the rollbar call, and part of that info is the route-resolution...which...then causes a `Rollbar.info`, etc etc etc)

I've traced it to the following stack, which shows that a call to `v2_conversion_for_photo_op?` calls Rollbar.info, which then calls `v2_conversion_for_photo_op?`.....

```
/app/lib/feature_flags.rb:64:in `v2_conversion_for_photo_op?'
/app/app/services/v2/feature_flag_constraint.rb:11:in `matches?'
/gems/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:40:in `block in matches?'
/gems/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:39:in `each'
/gems/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:39:in `all?'
/gems/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:39:in `matches?'
/gems/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:869:in `block in recognize_path_with_request'
/gems/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:75:in `block in recognize'
/gems/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:68:in `each'
/gems/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:68:in `recognize'
/gems/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:859:in `recognize_path_with_request'
/gems/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:855:in `recognize_path'
/gems/gems/rollbar-2.23.1/lib/rollbar/request_data_extractor.rb:224:in `rollbar_route_params'
/gems/gems/rollbar-2.23.1/lib/rollbar/request_data_extractor.rb:40:in `extract_request_data_from_rack'
/gems/gems/rollbar-2.23.1/lib/rollbar/middleware/rails/rollbar.rb:61:in `extract_request_data'
/gems/gems/rollbar-2.23.1/lib/rollbar/middleware/rails/rollbar.rb:53:in `request_data'
/gems/gems/rollbar-2.23.1/lib/rollbar/middleware/rails/rollbar.rb:46:in `block in fetch_scope'
/gems/gems/rollbar-2.23.1/lib/rollbar/lazy_store.rb:70:in `find_value'
/gems/gems/rollbar-2.23.1/lib/rollbar/lazy_store.rb:62:in `load_value'
/gems/gems/rollbar-2.23.1/lib/rollbar/lazy_store.rb:37:in `[]'
/gems/gems/rollbar-2.23.1/lib/rollbar/util.rb:99:in `block in perform_deep_merge'
/gems/gems/rollbar-2.23.1/lib/rollbar/lazy_store.rb:74:in `each_key'
/gems/gems/rollbar-2.23.1/lib/rollbar/lazy_store.rb:74:in `method_missing'
/gems/gems/rollbar-2.23.1/lib/rollbar/util.rb:94:in `perform_deep_merge'
/gems/gems/rollbar-2.23.1/lib/rollbar/util.rb:88:in `deep_merge'
/gems/gems/rollbar-2.23.1/lib/rollbar/item.rb:97:in `build_data'
/gems/gems/rollbar-2.23.1/lib/rollbar/item.rb:66:in `build'
/gems/gems/rollbar-2.23.1/lib/rollbar/notifier.rb:510:in `build_item'
/gems/gems/rollbar-2.23.1/lib/rollbar/notifier.rb:439:in `report'
/gems/gems/rollbar-2.23.1/lib/rollbar/notifier.rb:158:in `report_with_rescue'
/gems/gems/rollbar-2.23.1/lib/rollbar/notifier.rb:150:in `log'
/gems/gems/rollbar-2.23.1/lib/rollbar/notifier.rb:172:in `info'
/app/lib/feature_flags.rb:65:in `v2_conversion_for_photo_op?'
/app/app/services/v2/feature_flag_constraint.rb:11:in `matches?'
/gems/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:40:in `block in matches?'
```

For now, I'm removing the rollbar log in the route-resolution path, but I wanted to bring this up with you.

**Comment by waltjones** [comment]
@rdunlop Thank you for the report. I'll try to replicate. Was this working before updating to 2.23.1?

**Comment by rdunlop** [comment]
Thanks @waltjones . I also had this occurring on 2.22.1 (I upgraded to 2.23.1 today before submitting the report). I am not aware of a point where this behavior was working differently. I suspect that we've had this happening ever since we added the Constraint to our codebase.

**Comment by waltjones** [comment]
Good to know. Thank you!

**Comment by waltjones** [comment]
@rdunlop You should be able to do this by modifying the scope for Rollbar calls inside the constraint handler. Look here for more about scopes: https://docs.rollbar.com/docs/ruby#section-the-scope

By default, Rollbar-gem will try to add the route to the `context` key of the payload, and this evaluates the route, which calls the constraint handler, etc. Setting any other value for `context` in the current scope will override this and break the loop.

This would be roughly like:
```
Rollbar.scoped({ context: 'any useful data' }) do
  Rollbar.info("Nil entry")
end
```
Rollbar calls within the block should no longer try to evaluate the route. When the block exits, the original configuration is restored.
