### ISSUE TITLE
Deployment notification error in Ruby 1.9.3

### ISSUE THREAD

**Issue by jhanggi** [rollbar/rollbar-gem#945]
I'm getting an error when trying to do my capistrano deployment.

Here's the error:

```
  INFO Notifying Rollbar of deployment start
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ***@[redacted]: can't convert Symbol into String
/gems/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/gems/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
TypeError: can't convert Symbol into String
/usr/local/lib/ruby/1.9.1/net/http.rb:763:in `initialize'
/usr/local/lib/ruby/1.9.1/net/http.rb:763:in `open'
/usr/local/lib/ruby/1.9.1/net/http.rb:763:in `block in connect'
/usr/local/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
/usr/local/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
/usr/local/lib/ruby/1.9.1/net/http.rb:763:in `connect'
/usr/local/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
/usr/local/lib/ruby/1.9.1/net/http.rb:745:in `start'
/usr/local/lib/ruby/1.9.1/net/http.rb:557:in `start'
/gems/gems/rollbar-2.24.0/lib/rollbar/deploy.rb:46:in `send_request'
/gems/gems/rollbar-2.24.0/lib/rollbar/deploy.rb:24:in `report'
/gems/gems/rollbar-2.24.0/lib/rollbar/capistrano_tasks.rb:70:in `report_deploy_started'
/gems/gems/rollbar-2.24.0/lib/rollbar/capistrano_tasks.rb:9:in `block in deploy_started'
/gems/gems/rollbar-2.24.0/lib/rollbar/capistrano_tasks.rb:42:in `deploy_task'
/gems/gems/rollbar-2.24.0/lib/rollbar/capistrano_tasks.rb:8:in `deploy_started'
/gems/gems/rollbar-2.24.0/lib/rollbar/capistrano3.rb:16:in `block (3 levels) in <top (required)>'
/gems/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
/gems/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `run'
/gems/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => rollbar:deploy_started
The deploy has failed with an error: Exception while executing as ***@[redacted]: can't convert Symbol into String
** Invoke deploy:failed (first_time)
** Execute deploy:failed
** Invoke rollbar:deploy_failed (first_time)
** Execute rollbar:deploy_failed
  INFO Setting deployment status to `failed` in Rollbar
 ERROR Failed to update the deploy in Rollbar. No deploy id available.
```

I'm fairly certain this is an issue with Ruby 1.9.3 and it's implementation of Net::HTTP and proxies. 

I think the issue is 1.9.3 doesn't support `:ENV` for the proxy variable. If I remove the `opts[:proxy]` parameter in the call to `Net::HTTP.start` on `/lib/rollbar/deploy.rb:46`, the deployment succeeds. I'm not using a proxy, so I don't know the correct solution.

I'm using Rollbar gem version 2.24

**Comment by waltjones** [comment]
@jhanggi Thank you for the report. I'll take a look.
